Repository Requisitos-de-Software/2025.1-e-GDF, pull requests merged in 2025-05, with the labels that each got.

#82 Correção do App Selecionado e Lista de Apps
  docs/planejamento/aplicativos_selecionados.md
  docs/planejamento/app_selecionado.md
Labels: documentation

#78 Técnica de elitação: Brainstorming
  docs/assets/brainstorming.png
  docs/elicitacao/tec_elicitacao/brainstorming.md
  docs/elicitacao/tec_elicitacao/prototipacao.md
  mkdocs.yml
Labels: documentation

#84 Técnica de elicitação: Entrevista
  docs/elicitacao/tec_elicitacao/entrevista.md
Labels: documentation

#83 Docs/rich e-gdf
  docs/assets/pre-rastreabilidade/rich_picture.png
  docs/elicitacao/tec_elicitacao/introspeccao.md
  docs/pre-rastreabilidade/rich_picture.md
Labels: documentation

#81 Docs: Adicionando documentação da Sprint 1
  docs/planejamento/sprints/sprint0.md
  docs/planejamento/sprints/sprint1.md
Labels: documentation

#79 Docs/analise de documentos
  docs/assets/elicitacao/Analise_de_documentos/AD1.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD10.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD11.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD12.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD13.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD14.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD15.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD16.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD17.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD18.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD19.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD2.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD20.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD21.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD22.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD23.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD24.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD25.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD26.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD3.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD4.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD5.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD6.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD7.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD8.PNG
  docs/assets/elicitacao/Analise_de_documentos/AD9.PNG
  docs/elicitacao/tec_elicitacao/analise_documentos.md
Labels: documentation

#87 Perfil de usuário
  docs/elicitacao/perfil_de_usuario.md
Labels: documentation

#88 Requisitos Relacionados
  docs/elicitacao/req_elicitados.md
  docs/elicitacao/tec_elicitacao/introspeccao.md
  mkdocs.yml
Labels: documentation

#90 Adicionando nova funcionalidade de clicar na img
  .github/workflows/deploy-mkdocs.yml
  mkdocs.yml
Labels: enhancement

#85 Criação da Ata da Reunião — 18/04/2025
  docs/atas/ata05.md
  mkdocs.yml
Labels: documentation, ata

#97 First things first
  docs/assets/Tabela-First-things-First.png
  docs/elicitacao/tec_elicitacao/brainstorming.md
  docs/elicitacao/tec_priorizacao/first_things_first.md
  mkdocs.yml
Labels: documentation

#96 Docs: correções e informações de criptografia
  docs/elicitacao/tec_elicitacao/analise_documentos.md
Labels: documentation

#95 Técnica de priorização moscow
  docs/elicitacao/tec_elicitacao/entrevista.md
  docs/elicitacao/tec_priorizacao/moscow.md
  mkdocs.yml
Labels: documentation

#101 docs: Adicionando Perfil de usuário no git pages
  mkdocs.yml
Labels: documentation

#93 Docs/roi
  docs/elicitacao/tec_priorizacao/roi.md
Labels: documentation

#100 Documentação da técnica 100
  docs/elicitacao/tec_priorizacao/100.md
Labels: documentation

#102 docs: Adiciona caminho do ROI e 100$
  mkdocs.yml
Labels: documentation

#105 fix: Corrige nome do app
  docs/elicitacao/tec_priorizacao/roi.md
Labels: documentation

#108 Documentação da Segunda Apresentação
  docs/apresentacoes/apresentacao2.md
  docs/pre-rastreabilidade/rich_picture.md
  mkdocs.yml
Labels: documentation

#110 Docs/lista de verificação
  docs/inspecao/inspecao_2_grupo+1.md
  docs/inspecao/inspecao_2_grupo.md
  docs/verificacao/grupo/entrega02/entrega02grupo+1.md
  docs/verificacao/grupo/entrega02/entrega02grupo.md
  mkdocs.yml
Labels: documentation

#112 docs: adicao inspecao do grupo + 1
  docs/inspecao/inspecao_2_grupo+1.md
Labels: documentation

#116 Docs/arrumando inconsistencias
  docs/elicitacao/req_elicitados.md
  docs/elicitacao/tec_elicitacao/analise_documentos.md
  docs/elicitacao/tec_elicitacao/questionario.md
  docs/elicitacao/tec_priorizacao/100.md
Labels: documentation

#117 Docs/correcoes entrega2
  docs/assets/elicitacao/Entrevista/Entrevista-fonte1.png
  docs/assets/elicitacao/Entrevista/Entrevista-fonte2.png
  docs/assets/elicitacao/Entrevista/Entrevista-fonte3.png
  docs/elicitacao/tec_elicitacao/entrevista.md
  docs/planejamento/metodologia.md
Labels: documentation

#123 Correções após Apresentação 2
  docs/apresentacoes/apresentacao2.md
  docs/assets/brainstorming.png
  docs/assets/lista-2/Lista_Entrega2_Plano.png
  docs/assets/lista-2/Lista_Parte2_PlanoDeEnsino.png
  docs/atas/ata04.md
  docs/elicitacao/req_elicitados.md
  docs/elicitacao/tec_elicitacao/brainstorming.md
  docs/elicitacao/tec_priorizacao/first_things_first.md
  docs/verificacao/grupo/entrega02/entrega02grupo+1.md
  docs/verificacao/grupo/entrega02/entrega02grupo.md
  mkdocs.yml
Labels: documentation

#129 Criação de páginas e pastas para entrega 3
  docs/modelagem/casos_de_uso.md
  docs/modelagem/cenario.md
  docs/modelagem/especificacao_suplementar.md
  docs/modelagem/lexico.md
  mkdocs.yml
Labels: documentation

#115 Docs/correcao
  docs/inspecao/inspecao_2_grupo+1.md
Labels: documentation

#131 Cenários
  docs/assets/modelagem/Cenarios.png
  docs/assets/modelagem/Cenarios2.png
  docs/modelagem/cenario.md
Labels: documentation

#140 fix: Removendo link desatualizado do app e padronização do histórico …
  README.md
Labels: bug, documentation

#141 Correção dos cenários
  docs/modelagem/cenario.md
Labels: documentation

#130 Criação do documento UML casos de uso
  docs/assets/modelagem/casos_de_uso/diagrama_casos_de_uso.png
  docs/modelagem/casos_de_uso.md
  docs/planejamento/ferramentas.md
Labels: documentation

#143 Especificação Suplementar
  docs/assets/modelagem/especificacao.png
  docs/assets/modelagem/especificações.png
  docs/modelagem/especificacao_suplementar.md
  docs/planejamento/termos_de_uso.md
Labels: documentation

#144 Docs/lexico
  docs/assets/modelagem/lexico-fonte1.png
  docs/assets/modelagem/lexico-fonte2.png
  docs/assets/modelagem/lexico-fonte3.png
  docs/assets/modelagem/lexico-fonte4.png
  docs/assets/modelagem/lexico-fonte5.png
  docs/modelagem/lexico.md
Labels: documentation

#136 Docs/ata 09 05 2025
  docs/atas/ata07.md
Labels: ata

#135 fix: Adição de hyperlinks de rastreabilidade nas tabelas de requisitos
  docs/elicitacao/tec_priorizacao/roi.md
Labels: documentation, enhancement

#155 Docs/lexico
  docs/modelagem/lexico.md
Labels: documentation

#157 Criação de Checklists para Verificação de Artefatos de Requisitos
  docs/assets/lista-3/F1.PNG
  docs/assets/lista-3/F2.PNG
  docs/assets/lista-3/F7.PNG
  docs/assets/lista-3/ListaCenarios.png
  docs/assets/lista-3/listadoprof1-10.png
  docs/assets/lista-3/listadoprof11-18.png
  docs/assets/modelagem/Léxico1.png
  docs/assets/modelagem/Léxico10.png
  docs/assets/modelagem/Léxico11.png
  docs/assets/modelagem/Léxico12.png
  docs/assets/modelagem/Léxico13.png
  docs/assets/modelagem/Léxico14.png
  docs/assets/modelagem/Léxico15.png
  docs/assets/modelagem/Léxico2.png
  docs/assets/modelagem/Léxico3.png
  docs/assets/modelagem/Léxico4.png
  docs/assets/modelagem/Léxico5.png
  docs/assets/modelagem/Léxico6.png
  docs/assets/modelagem/Léxico7.png
  docs/assets/modelagem/Léxico8.png
  docs/assets/modelagem/Léxico9.png
  docs/assets/modelagem/ref1.png
  docs/assets/modelagem/ref10.png
  docs/assets/modelagem/ref2.png
  docs/assets/modelagem/ref3.png
  docs/assets/modelagem/ref4.png
  docs/assets/modelagem/ref5.png
  docs/assets/modelagem/ref6.png
  docs/assets/modelagem/ref7.png
  docs/assets/modelagem/ref8.png
  docs/assets/modelagem/ref9.png
  docs/inspecao/inspecao_3_grupo+1.md
  docs/inspecao/inspecao_3_grupo.md
  docs/verificacao/grupo/entrega03/entrega03grupo+1.md
  docs/verificacao/grupo/entrega03/entrega03grupo.md
  mkdocs.yml
Labels: documentation

#159 Adicionando video da inspeção
  docs/inspecao/inspecao_3_grupo.md
  docs/modelagem/casos_de_uso.md
Labels: documentation

#160 Docs/correcao geral
  docs/apresentacoes/apresentacao3.md
  mkdocs.yml
Labels: documentation, ponto de controle

#162 Docs/cron exec
  docs/planejamento/cronograma_executado.md
Labels: documentation

#146 Docs/arrumando req
  docs/elicitacao/req_elicitados.md
Labels: documentation

#163 docs: ajustes no pc3
  docs/planejamento/cronograma_executado.md
Labels: documentation

#167 docs: Adiciona link de inspeção do grupo 9
  docs/inspecao/inspecao_3_grupo+1.md
Labels: documentation, inspeção

#170 Ata 8
  docs/atas/ata08.md
  mkdocs.yml
Labels: ata

#171 Organização das pastas backlog história de usuário e nfr framework no mkdocs
  docs/modelagem/agil/backog.md
  docs/modelagem/agil/historia-de-usuario.md
  docs/modelagem/agil/nfrframework.md
  docs/modelagem/casos_de_uso.md
  mkdocs.yml
Labels: documentation
